# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2

project_name: dst

before:
  hooks:
    - go mod download

builds:
  - main: ./cmd/dst
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    binary: dst
    mod_timestamp: '{{ .CommitTimestamp }}'

archives:
  - format: tar.gz
    name_template: '{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'

changelog:
  sort: asc
  filters:
    exclude:
      - '^chore'
      - '^ci'
      - '^docs'
      - '^test'
      - '^Merge pull request'
