name: directus-schema-types

# Do not change these values
# Use compose.override.yml
services:
  directus:
    image: directus/directus:11
    ports:
      - 8055:8055
    env_file:
      - .env.example
