// File generated by directus-schema-types. Do not change.

export type DirectusMigrationsPrimaryKey = string;
export type DirectusMigrationsPrimaryKeyField = 'version';

export interface DirectusMigrations {
    /**
     * Type: string
     */
    name?: string;
    /**
     * Type: dateTime
     */
    timestamp?: Date | null;
    /**
     * Type: string
     */
    version?: DirectusMigrationsPrimaryKey;
}

export interface DirectusMigrationsRelations {}

export interface DirectusMigrationsRelatedCollections {}

export interface DirectusMigrationsPayload extends Omit<DirectusMigrations, 'timestamp'> {
    timestamp?: string | null;
}

/**
 * parseDirectusMigrationsPayload parses the given {@link DirectusMigrationsPayload} payload.
 * @param v The payload to parse.
 * @returns The payload parsed to {@link DirectusMigrations}.
 */
export function parseDirectusMigrationsPayload(v: DirectusMigrationsPayload): DirectusMigrations {
    const r = v as Record<keyof DirectusMigrations, unknown>;
    if (v.timestamp) {
        r.timestamp = new Date(v.timestamp);
    }
    return r as DirectusMigrations;
}

/**
 * parseDirectusMigrations parses the given {@link DirectusMigrations}.
 * @param v The object to parse.
 * @returns The payload {@link DirectusMigrationsPayload}.
 */
export function parseDirectusMigrations(v: DirectusMigrations): DirectusMigrationsPayload {
    const r = v as Record<keyof DirectusMigrationsPayload, unknown>;
    if (v.timestamp) {
        r.timestamp = v.timestamp.toString();
    }
    return r as DirectusMigrationsPayload;
}
