// File generated by directus-schema-types. Do not change.

import { DirectusFlowsPrimaryKey, DirectusFlows } from './directus_flows';

// --- directus_webhooks ---

export type DirectusWebhooksPrimaryKeyField = 'id';
export type DirectusWebhooksPrimaryKey = number;

export interface DirectusWebhooks {
    // Type: csv
    actions?: any;

    // Type: csv
    collections?: any;

    // Type: boolean
    data?: boolean;

    // Type: json
    headers?: object | null;

    // Type: integer
    id?: number;

    // Type: string
    method?: string;

    // Type: string
    migrated_flow?: string | null;

    // Type: string
    name?: string;

    // Type: string
    status?: string;

    // Type: string
    url?: string;

    // Type: boolean
    was_active_before_deprecation?: boolean;
}

export interface DirectusWebhooksRelations {
    migrated_flow: DirectusFlowsPrimaryKey | DirectusFlows;
}

/**
 * DirectusWebhooksRelatedCollections maps the {@link DirectusWebhooksRelations}
 * fields to the name of the related collection.
 */
export interface DirectusWebhooksRelatedCollections {
    migrated_flow: 'directus_flows';
}

// The payload is the same as the schema definition.
export type DirectusWebhooksPayload = DirectusWebhooks;

/**
 * @param v The payload to parse.
 * @returns The payload as it is received: it is the same as the schema definition.
 */
export function parseDirectusWebhooksPayload(v: DirectusWebhooksPayload): DirectusWebhooks {
    return v;
}
