// File generated by directus-schema-types. Do not change.

import { RecipesPrimaryKey, Recipes } from './recipes';

// --- chefs ---

export type ChefsPrimaryKeyField = 'id';
export type ChefsPrimaryKey = number;

export interface Chefs {
    // Type: integer
    readonly id?: number;

    // Type: integer
    signature_dish?: number | null;
}

export interface ChefsRelations {
    signature_dish: RecipesPrimaryKey | Recipes;
}
