// File generated by directus-schema-types. Do not change.

import { DirectusRolesPrimaryKey, DirectusRoles } from './directus_roles';
import { DirectusUsersPrimaryKey, DirectusUsers } from './directus_users';

// --- directus_presets ---

export type DirectusPresetsPrimaryKeyField = 'id';
export type DirectusPresetsPrimaryKey = number;

export interface DirectusPresets {
    // Type: string
    bookmark?: string | null;

    // Type: string
    collection?: string | null;

    // Type: string
    color?: string | null;

    // Type: json
    filter?: object | null;

    // Type: string
    icon?: string | null;

    // Type: integer
    id?: number;

    // Type: string
    layout?: string | null;

    // Type: json
    layout_options?: object | null;

    // Type: json
    layout_query?: object | null;

    // Type: integer
    refresh_interval?: number | null;

    // Type: string
    role?: string | null;

    // Type: string
    search?: string | null;

    // Type: string
    user?: string | null;
}

export interface DirectusPresetsRelations {
    role: DirectusRolesPrimaryKey | DirectusRoles;

    user: DirectusUsersPrimaryKey | DirectusUsers;
}

// The payload is the same as the schema definition.
export type DirectusPresetsPayload = DirectusPresets;

/**
 * @param v The payload to parse.
 * @returns The payload as it is received: it is the same as the schema definition.
 */
export function parseDirectusPresetsPayload(v: DirectusPresetsPayload): DirectusPresets {
    return v;
}
