// File generated by directus-schema-types. Do not change.

import { DirectusFilesPrimaryKey, DirectusFiles } from './directus_files';
import { DirectusFoldersPrimaryKey, DirectusFolders } from './directus_folders';
import { DirectusRolesPrimaryKey, DirectusRoles } from './directus_roles';

// --- directus_settings ---

export type DirectusSettingsPrimaryKeyField = 'id';
export type DirectusSettingsPrimaryKey = number;

export interface DirectusSettings {
    // Type: integer
    auth_login_attempts?: number | null;

    // Type: string
    auth_password_policy?: string | null;

    // Type: json
    basemaps?: object | null;

    // Type: json
    custom_aspect_ratios?: object | null;

    // Type: text
    custom_css?: string | null;

    // Type: string
    default_appearance?: string;

    // Type: string
    default_language?: string;

    // Type: string
    default_theme_dark?: string | null;

    // Type: string
    default_theme_light?: string | null;

    // Type: integer
    id?: number;

    // Type: string
    mapbox_key?: string | null;

    // Type: json
    module_bar?: object | null;

    // $t:field_options.directus_settings.project_color_note
    // Type: string
    project_color?: string;

    // Type: string
    project_descriptor?: string | null;

    // $t:field_options.directus_settings.project_logo_note
    // Type: string
    project_logo?: string | null;

    // Type: string
    project_name?: string;

    // Type: string
    project_url?: string | null;

    // Type: string
    public_background?: string | null;

    // $t:field_options.directus_settings.project_favicon_note
    // Type: string
    public_favicon?: string | null;

    // Type: string
    public_foreground?: string | null;

    // Type: text
    public_note?: string | null;

    // $t:fields.directus_settings.public_registration_note
    // Type: boolean
    public_registration?: boolean;

    // $t:fields.directus_settings.public_registration_email_filter_note
    // Type: json
    public_registration_email_filter?: object | null;

    // $t:fields.directus_settings.public_registration_role_note
    // Type: string
    public_registration_role?: string | null;

    // $t:fields.directus_settings.public_registration_verify_email_note
    // Type: boolean
    public_registration_verify_email?: boolean;

    // Type: string
    report_bug_url?: string | null;

    // Type: string
    report_error_url?: string | null;

    // Type: string
    report_feature_url?: string | null;

    // Type: json
    storage_asset_presets?: object | null;

    // Type: string
    storage_asset_transform?: string | null;

    // $t:interfaces.system-folder.field_hint
    // Type: string
    storage_default_folder?: string | null;

    // Type: json
    theme_dark_overrides?: object | null;

    // Type: json
    theme_light_overrides?: object | null;
}

export interface DirectusSettingsRelations {
    project_logo: DirectusFilesPrimaryKey | DirectusFiles;

    public_background: DirectusFilesPrimaryKey | DirectusFiles;

    public_favicon: DirectusFilesPrimaryKey | DirectusFiles;

    public_foreground: DirectusFilesPrimaryKey | DirectusFiles;

    public_registration_role: DirectusRolesPrimaryKey | DirectusRoles;

    storage_default_folder: DirectusFoldersPrimaryKey | DirectusFolders;
}

// The payload is the same as the schema definition.
export type DirectusSettingsPayload = DirectusSettings;

/**
 * @param v The payload to parse.
 * @returns The payload as it is received: it is the same as the schema definition.
 */
export function parseDirectusSettingsPayload(v: DirectusSettingsPayload): DirectusSettings {
    return v;
}
