// File generated by directus-schema-types. Do not change.

import { DirectusPoliciesPrimaryKey, DirectusPolicies } from './directus_policies';
import { DirectusRolesPrimaryKey, DirectusRoles } from './directus_roles';
import { DirectusUsersPrimaryKey, DirectusUsers } from './directus_users';

// --- directus_access ---

export type DirectusAccessPrimaryKeyField = 'id';
export type DirectusAccessPrimaryKey = string;

export interface DirectusAccess {
    // Type: uuid
    id?: string | null;

    // Type: string
    policy?: string;

    // Type: string
    role?: string | null;

    // Type: integer
    sort?: number | null;

    // Type: string
    user?: string | null;
}

export interface DirectusAccessRelations {
    policy: DirectusPoliciesPrimaryKey | DirectusPolicies;

    role: DirectusRolesPrimaryKey | DirectusRoles;

    user: DirectusUsersPrimaryKey | DirectusUsers;
}
