// File generated by directus-schema-types. Do not change.

// --- directus_translations ---

export type DirectusTranslationsPrimaryKeyField = 'id';
export type DirectusTranslationsPrimaryKey = string;

export interface DirectusTranslations {
    // Type: uuid
    id?: string;

    // Type: string
    key: string;

    // Type: string
    language: string;

    // Type: text
    value: string;
}

export interface DirectusTranslationsRelations {}
