// File generated by directus-schema-types. Do not change.

import { DirectusRevisionsPrimaryKey, DirectusRevisions } from './directus_revisions';
import { DirectusUsersPrimaryKey, DirectusUsers } from './directus_users';

// --- directus_activity ---

export type DirectusActivityPrimaryKeyField = 'id';
export type DirectusActivityPrimaryKey = number;

export interface DirectusActivity {
    // Type: string
    action?: string;

    // Type: string
    collection?: string;

    // Type: text
    comment?: string | null;

    // Type: integer
    id?: number;

    // Type: string
    ip?: string | null;

    // Type: string
    item?: string;

    // Type: string
    origin?: string | null;

    // Type: timestamp
    timestamp?: Date;

    // Type: string
    user?: string | null;

    // Type: text
    user_agent?: string | null;
}

export interface DirectusActivityRelations {
    revisions: (DirectusRevisionsPrimaryKey | DirectusRevisions)[];

    user: DirectusUsersPrimaryKey | DirectusUsers;
}
