// File generated by directus-schema-types. Do not change.

import { DirectusPoliciesPrimaryKey, DirectusPolicies } from './directus_policies';

// --- directus_permissions ---

export type DirectusPermissionsPrimaryKeyField = 'id';
export type DirectusPermissionsPrimaryKey = number;

export interface DirectusPermissions {
    // Type: string
    action?: string;

    // Type: string
    collection?: string;

    // Type: csv
    fields?: any | null;

    // Type: integer
    id?: number;

    // Type: json
    permissions?: object | null;

    // Type: string
    policy?: string;

    // Type: json
    presets?: object | null;

    // Type: json
    validation?: object | null;
}

export interface DirectusPermissionsRelations {
    policy: DirectusPoliciesPrimaryKey | DirectusPolicies;
}

// The payload is the same as the schema definition.
export type DirectusPermissionsPayload = DirectusPermissions;

/**
 * @param v The payload to parse.
 * @returns The payload as it is received: it is the same as the schema definition.
 */
export function parseDirectusPermissionsPayload(v: DirectusPermissionsPayload): DirectusPermissions {
    return v;
}
