// File generated by directus-schema-types. Do not change.

import { DirectusFlowsPrimaryKey, DirectusFlows } from './directus_flows';

// --- directus_webhooks ---

export type DirectusWebhooksPrimaryKeyField = 'id';
export type DirectusWebhooksPrimaryKey = number;

export interface DirectusWebhooks {
    // Type: csv
    actions?: any;

    // Type: csv
    collections?: any;

    // Type: boolean
    data?: boolean;

    // Type: json
    headers?: object | null;

    // Type: integer
    id?: number;

    // Type: string
    method?: string;

    // Type: string
    migrated_flow?: string | null;

    // Type: string
    name?: string;

    // Type: string
    status?: string;

    // Type: string
    url?: string;

    // Type: boolean
    was_active_before_deprecation?: boolean;
}

export interface DirectusWebhooksRelations {
    migrated_flow: DirectusFlowsPrimaryKey | DirectusFlows;
}
