// File generated by directus-schema-types. Do not change.

import { DirectusDashboardsPrimaryKey, DirectusDashboards } from './directus_dashboards';
import { DirectusUsersPrimaryKey, DirectusUsers } from './directus_users';

// --- directus_panels ---

export type DirectusPanelsPrimaryKeyField = 'id';
export type DirectusPanelsPrimaryKey = string;

export interface DirectusPanels {
    // Type: string
    color?: string | null;

    // Type: string
    dashboard?: string;

    // Type: timestamp
    date_created?: Date | null;

    // Type: integer
    height?: number;

    // Type: string
    icon?: string | null;

    // Type: uuid
    id?: string;

    // Type: string
    name?: string | null;

    // Type: text
    note?: string | null;

    // Type: json
    options?: object | null;

    // Type: integer
    position_x?: number;

    // Type: integer
    position_y?: number;

    // Type: boolean
    show_header?: boolean;

    // Type: string
    type?: string;

    // Type: string
    user_created?: string | null;

    // Type: integer
    width?: number;
}

export interface DirectusPanelsRelations {
    dashboard: DirectusDashboardsPrimaryKey | DirectusDashboards;

    user_created: DirectusUsersPrimaryKey | DirectusUsers;
}
