// File generated by directus-schema-types. Do not change.

// --- directus_translations ---

export type DirectusTranslationsPrimaryKeyField = 'id';
export type DirectusTranslationsPrimaryKey = string;

export interface DirectusTranslations {
    // Type: uuid
    id?: string;

    // Type: string
    key: string;

    // Type: string
    language: string;

    // Type: text
    value: string;
}

export interface DirectusTranslationsRelations {}

// The payload is the same as the schema definition.
export type DirectusTranslationsPayload = DirectusTranslations;

/**
 * @param v The payload to parse.
 * @returns The payload as it is received: it is the same as the schema definition.
 */
export function parseDirectusTranslationsPayload(v: DirectusTranslationsPayload): DirectusTranslations {
    return v;
}
