// File generated by directus-schema-types. Do not change.

// --- directus_migrations ---

export type DirectusMigrationsPrimaryKeyField = 'version';
export type DirectusMigrationsPrimaryKey = string;

export interface DirectusMigrations {
    // Type: string
    name?: string;

    // Type: dateTime
    timestamp?: Date | null;

    // Type: string
    version?: string;
}

export interface DirectusMigrationsRelations {}
