// File generated by directus-schema-types. Do not change.

import { DirectusAccessPrimaryKey, DirectusAccess } from './directus_access';
import { DirectusUsersPrimaryKey, DirectusUsers } from './directus_users';

// --- directus_roles ---

export type DirectusRolesPrimaryKeyField = 'id';
export type DirectusRolesPrimaryKey = string;

export interface DirectusRoles {
    // Type: text
    description?: string | null;

    // Type: string
    icon?: string;

    // Type: uuid
    id?: string;

    // Type: string
    name: string;

    // $t:field_options.directus_roles.parent_note
    // Type: string
    parent?: string | null;
}

export interface DirectusRolesRelations {
    children: (DirectusRolesPrimaryKey | DirectusRoles)[];

    parent: DirectusRolesPrimaryKey | DirectusRoles;

    policies: (DirectusAccessPrimaryKey | DirectusAccess)[];

    users: (DirectusUsersPrimaryKey | DirectusUsers)[];
}
