// File generated by directus-schema-types. Do not change.

// --- directus_folders ---

export type DirectusFoldersPrimaryKeyField = 'id';
export type DirectusFoldersPrimaryKey = string;

export interface DirectusFolders {
    // Type: uuid
    id?: string;

    // Type: string
    name?: string;

    // Type: string
    parent?: string | null;
}

export interface DirectusFoldersRelations {
    parent: DirectusFoldersPrimaryKey | DirectusFolders;
}
