// File generated by directus-schema-types. Do not change.

import { IngredientsPrimaryKey, Ingredients } from './ingredients';
import { RecipesPrimaryKey, Recipes } from './recipes';

// --- recipes_ingredients ---

export type RecipesIngredientsPrimaryKeyField = 'id';
export type RecipesIngredientsPrimaryKey = number;

export interface RecipesIngredients {
    // Type: integer
    id?: number;

    // Type: integer
    ingredients_id?: number | null;

    // Type: integer
    recipes_id?: number | null;
}

export interface RecipesIngredientsRelations {
    ingredients_id: IngredientsPrimaryKey | Ingredients;

    recipes_id: RecipesPrimaryKey | Recipes;
}
