name: CI
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/ci.yml
      - 'go.mod'
      - 'go.sum'
      - '**.go'
      - '**.tmpl'
  pull_request:
    paths:
      - .github/workflows/ci.yml
      - 'go.mod'
      - 'go.sum'
      - '**.go'
      - '**.tmpl'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest

  test:
    strategy:
      matrix:
        # @TODO
        # Test with different os.
        # Currently not possible because docker is available only on Linux.
        os: ['ubuntu-latest']
        # @TODO
        # Test with different Directus versions.
        directusVersion: ['11.1.0']
        include:
          - # enable coverage for the default os and Directus version.
            coverage: true
            os: 'ubuntu-latest'
            directusVersion: '11.1.0'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Test
        env:
          DIRECTUS_VERSION: ${{ matrix.directusVersion }}
          DIRECTUS_DB_VENDOR: 'sqlite'
        run: >-
          go test -v -race
          -covermode=atomic
          -coverprofile=coverage.out
          -coverpkg=./...
          ./...
      - name: Upload coverage reports to Codecov
        if: ${{ matrix.coverage }}
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
